# Generated by Django 5.2.15 on 2026-06-13 12:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notification_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['priority', '-created_at']},
        ),
        migrations.AddField(
            model_name='notification',
            name='priority',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Broadcast'), (2, 'Mention'), (3, 'Direct Message'), (4, 'Channel Message')], default=4),
        ),
        migrations.AddField(
            model_name='notification',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_notifications', to=settings.AUTH_USER_MODEL),
        ),
    ]
