# Generated by Django 5.2.15 on 2026-06-13 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_chatmessage_reply_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='original_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
