# Generated by Django 5.2.15 on 2026-06-13 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_chatmessage_original_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='broadcast_channels',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='broadcast_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='is_broadcast',
            field=models.BooleanField(default=False),
        ),
    ]
