# Generated by Django 5.2.15 on 2026-06-10 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('channels_app', '0002_teamchannel_is_archived_alter_teamchannel_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teamchannel',
            name='is_archived',
        ),
    ]
