# Generated by Django 5.2.15 on 2026-06-13 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels_app', '0003_remove_teamchannel_is_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamchannel',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teamchannel',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='teamchannel',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
